esphome:
  name: lilka
  friendly_name: lilka
  on_boot:
    priority: 600
    then:
      - output.turn_on: display_power
      - delay: 100ms

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "Lilka Fallback Hotspot"
    password: "hnYImYM4O6I0"

captive_portal:
web_server:
api:
  encryption:
    key: "Yw3yq8lxsaze+jdggjAwxKpV4GD6gNZptvw4d6OPfOc="

logger:
  level: INFO
  logs:
    lvgl: WARN

ota:
  - platform: esphome
    password: "bb198feb99159fdaefc8092f10039acd"

output:
  - platform: gpio
    pin: 46
    id: display_power

spi:
  clk_pin: 18
  mosi_pin: 17

display:
  - platform: mipi_spi
    model: ST7789V
    id: my_display
    dc_pin: 15
    cs_pin: 7
    update_interval: 2s
    rotation: 270
    invert_colors: true
    color_order: BGR
    pixel_mode: 16bit
    dimensions:
      width: 280
      height: 240
      offset_width: 20
    auto_clear_enabled: false

lvgl:
  encoders:
    - enter_button: enter_key
      id: encoder_id
      sensor:
        left_button: left_key
        right_button: right_key
  theme:
    label:
      align: center
      text_align: center
      text_font: MONTSERRAT_24
    button:
      width: 80%
      bg_color: grey
      text_color: black
      border_width: 2
      border_opa: transp
      radius: 6
      focus_key:
        border_color: white
        border_opa: cover
      checked:
        bg_color: orange
  pages:
    - id: main_page
      bg_color: black
      pad_all: 20
      layout:
        type: FLEX
        flex_flow: COLUMN
        flex_align_main: SPACE_EVENLY
        flex_align_cross: CENTER
      widgets:
        - button:
            id: bathroom_button
            checkable: true
            widgets:
              - label:
                  text: "Bathroom"
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: light.tz3000_qewo8dlz_ts0013_light
        - button:
            id: pantry_button
            checkable: true
            widgets:
              - label:
                  text: "Pantry"
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: light.tz3000_qewo8dlz_ts0013_light_2
        - button:
            id: kitchen_button
            checkable: true
            widgets:
              - label:
                  text: "Kitchen"
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: light.tz3000_qewo8dlz_ts0013_light_3

binary_sensor:
  - platform: homeassistant
    id: bathroom_light
    entity_id: light.tz3000_qewo8dlz_ts0013_light
    internal: true
    on_state:
      - lvgl.widget.update:
          id: bathroom_button
          state:
            checked: !lambda 'return id(bathroom_light).state;'
  - platform: homeassistant
    id: pantry_light
    entity_id: light.tz3000_qewo8dlz_ts0013_light_2
    internal: true
    on_state:
      - lvgl.widget.update:
          id: pantry_button
          state:
            checked: !lambda 'return id(pantry_light).state;'
  - platform: homeassistant
    id: kitchen_light
    entity_id: light.tz3000_qewo8dlz_ts0013_light_3
    internal: true
    on_state:
      - lvgl.widget.update:
          id: kitchen_button
          state:
            checked: !lambda 'return id(kitchen_light).state;'
  - platform: gpio
    pin:
      number: 38
      mode: INPUT_PULLUP
      inverted: true
    id: left_key
  - platform: gpio
    pin:
      number: 41
      mode: INPUT_PULLUP
      inverted: true
    id: right_key
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    id: enter_key
