esphome:
  name: lilka
  friendly_name: lilka
  on_boot:
    priority: 600
    then:
      - output.turn_on: display_power
      - delay: 100ms

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
  flash_size: 16MB

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "Lilka Fallback Hotspot"
    password: "hnYImYM4O6I0"

captive_portal:

web_server:

api:
  encryption:
    key: "Yw3yq8lxsaze+jdggjAwxKpV4GD6gNZptvw4d6OPfOc="

logger:
  level: INFO
  logs:
    lvgl: WARN

ota:
  - platform: esphome
    password: "bb198feb99159fdaefc8092f10039acd"

output:
  - platform: gpio
    pin: 46
    id: display_power
  
  - platform: ledc
    pin: 11
    id: rtttl_out

rtttl:
  output: rtttl_out
  id: my_rtttl
  on_finished_playback:
    - logger.log: 'Мелодія закінчилась!'

spi:
  clk_pin: 18
  mosi_pin: 17

display:
  - platform: mipi_spi
    model: ST7789V
    id: my_display
    dc_pin: 15
    cs_pin: 7
    update_interval: 2s
    rotation: 270
    invert_colors: true
    color_order: BGR
    pixel_mode: 16bit
    dimensions:
      width: 280
      height: 240
      offset_width: 20
    auto_clear_enabled: false

lvgl:
  encoders:
    - enter_button: enter_key
      id: encoder_id
      sensor:
        left_button: left_key
        right_button: right_key
  theme:
    label:
      align: center
      text_align: center
      text_font: MONTSERRAT_24
    button:
      width: 80%
      bg_color: grey
      text_color: black
      border_width: 2
      border_opa: transp
      radius: 6
      focus_key:
        border_color: white
        border_opa: cover
      checked:
        bg_color: orange
  pages:
    - id: main_page
      bg_color: black
      pad_all: 20
      layout:
        type: FLEX
        flex_flow: COLUMN
        flex_align_main: SPACE_EVENLY
        flex_align_cross: CENTER
      widgets:
        - button:
            id: mario_button
            checkable: false
            widgets:
              - label:
                  text: "Mario"
            on_click:
              - if:
                  condition:
                    rtttl.is_playing:
                      id: my_rtttl
                  then:
                    - rtttl.stop:
                        id: my_rtttl
                  else:
                    - rtttl.play: 
                        id: my_rtttl
                        rtttl: 'mario:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,16p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b'
        
        - button:
            id: starwars_button
            checkable: false
            widgets:
              - label:
                  text: "Star Wars"
            on_click:
              - if:
                  condition:
                    rtttl.is_playing:
                      id: my_rtttl
                  then:
                    - rtttl.stop:
                        id: my_rtttl
                  else:
                    - rtttl.play:
                        id: my_rtttl
                        rtttl: 'star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p'
        - button:
            id: mission_button
            checkable: false
            widgets:
              - label:
                  text: "Miss Impossible"
            on_click:
              - if:
                  condition:
                    rtttl.is_playing:
                      id: my_rtttl
                  then:
                    - rtttl.stop:
                        id: my_rtttl
                  else:
                    - rtttl.play:
                        id: my_rtttl
                        rtttl: 'mission_imp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d'

binary_sensor:
  - platform: gpio
    pin:
      number: 38
      mode: INPUT_PULLUP
      inverted: true
    id: left_key
  
  - platform: gpio
    pin:
      number: 41
      mode: INPUT_PULLUP
      inverted: true
    id: right_key
  
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    id: enter_key